In [73]:
import importlib
import preprocessing as pre
import pandas as pd
import data_loader
import user_profile as user_pf

importlib.reload(pre)
importlib.reload(data_loader)

In [36]:
# Load the data
films_df = data_loader.load_movies()
ratings_df = data_loader.load_ratings()
credits_df = data_loader.load_credits()

In [55]:

films_df = data_loader.load_movies()

In [56]:
films_df.head()

,id,title,vote_average,vote_count,release_date,popularity,genres
0,2,Ariel,7.1,340.0,1988-10-21,9.400,"Comedy, Drama, Romance, Crime"
1,3,Shadows in Paradise,7.3,403.0,1986-10-17,7.088,"Comedy, Drama, Romance"
2,5,Four Rooms,5.9,2678.0,1995-12-09,3.547,"Comedy, Crime"
3,6,Judgment Night,6.5,333.0,1993-10-15,12.110,"Action, Crime, Thriller"
4,8,Life in Loops (A Megacities RMX),7.5,27.0,2006-01-01,3.203,Documentary

In [70]:

print("Data dimensions:")
print("films_df: ", films_df.shape)
print("ratings_df: ", ratings_df.shape)
print("credits_df: ", credits_df.shape)

Data dimensions:
films_df:  (88799, 7)
ratings_df:  (32000204, 3)
credits_df:  (45476, 3)

In [74]:

ratings_df = data_loader.load_ratings()

In [76]:
ratings_df.sort_values(by='timestamp', inplace=True, ascending=False)

In [87]:
ratings_df.head(20)

          userId  movieId  rating   timestamp
8663645    54315   116989     2.5  1697164147
8663606    54315   104457     2.5  1697164098
8663785    54315   194947     2.5  1697164060
8663791    54315   197709     3.5  1697163970
8663629    54315   112818     3.0  1697163923
18193845  113786   258451     3.0  1697163799
10512685   65905   291857     3.5  1697163675
25145022  157901   292349     3.0  1697163414
29853809  187240     4901     3.5  1697163251
26148753  164287     6803     3.5  1697163008
10532451   66022    33162     3.0  1697162967
26148661  164287     4789     3.5  1697162955
16652465  104388   277066     4.0  1697162877
31923114  200443     6711     3.5  1697162874
16652256  104388     5791     2.0  1697162808
26148712  164287     5715     3.0  1697162775
16652421  104388   193065     4.5  1697162772
26148812  164287     8607     3.5  1697162734
16652472  104388   279762     2.5  1697162639
16652463  104388   276361     4.5  1697162634

In [78]:
# Convert the timestamp to a datetime object
ratings_slice = ratings_df[:100]
ratings_slice['timestamp'] = pd.to_datetime(ratings_slice['timestamp'], unit='s')

/var/folders/lr/44zcpqfx2196g_qy5t3kc7m40000gp/T/ipykernel_10563/1476681398.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ratings_slice['timestamp'] = pd.to_datetime(ratings_slice['timestamp'], unit='s')

In [88]:
ratings_slice.head(20)

          userId  movieId  rating           timestamp
8663645    54315   116989     2.5 2023-10-13 02:29:07
8663606    54315   104457     2.5 2023-10-13 02:28:18
8663785    54315   194947     2.5 2023-10-13 02:27:40
8663791    54315   197709     3.5 2023-10-13 02:26:10
8663629    54315   112818     3.0 2023-10-13 02:25:23
18193845  113786   258451     3.0 2023-10-13 02:23:19
10512685   65905   291857     3.5 2023-10-13 02:21:15
25145022  157901   292349     3.0 2023-10-13 02:16:54
29853809  187240     4901     3.5 2023-10-13 02:14:11
26148753  164287     6803     3.5 2023-10-13 02:10:08
10532451   66022    33162     3.0 2023-10-13 02:09:27
26148661  164287     4789     3.5 2023-10-13 02:09:15
16652465  104388   277066     4.0 2023-10-13 02:07:57
31923114  200443     6711     3.5 2023-10-13 02:07:54
16652256  104388     5791     2.0 2023-10-13 02:06:48
26148712  164287     5715     3.0 2023-10-13 02:06:15
16652421  104388   193065     4.5 2023-10-13 02:06:12
26148812  164287     8607     3.5 2023-10-13 02:05:34
16652472  104388   279762     2.5 2023-10-13 02:03:59
16652463  104388   276361     4.5 2023-10-13 02:03:54

In [96]:
# Get movie 116989 
films_df[films_df['id'] == 100]

,id,title,vote_average,vote_count,release_date,popularity,genres
65,100,"Lock, Stock and Two Smoking Barrels",8.115,6692.0,1998-08-28,1.946,"Comedy, Crime"

In [58]:
# Drop any entries with under 10 votes
films_df = films_df[films_df['vote_count'] >= 10]
print("films_df: ", films_df.shape)

films_df:  (88799, 7)

In [50]:
# remove all films released before 1985
films_df = films_df[pd.to_datetime(films_df['release_date']).dt.year >= 1985]

In [98]:
films_df['genres'].head()

304132              Family, Fantasy
939885            Animation, Action
1042445                      Comedy
816002      Action, Crime, Thriller
720478     Comedy, Horror, Thriller
Name: genres, dtype: object

In [51]:
print("films_df: ", films_df.shape)

films_df:  (733750, 7)

In [ ]:
ohe_films_df, genre_list_mlb = pre.one_hot_encode_genres(films_df)

In [86]:
# Get movie 116989 
ohe_films_df[ohe_films_df['id'] == 112818]

Empty DataFrame
Columns: [id, popularity, release_date, title, vote_average, vote_count, Action, Adventure, Animation, Comedy, Crime, Documentary, Drama, Family, Fantasy, Foreign, History, Horror, Music, Mystery, Romance, Science Fiction, TV Movie, Thriller, War, Western]
Index: []

[0 rows x 26 columns]

In [53]:
films_df = pre.data_tidying(films_df, credits_df)
print(films_df.columns)

Index(['id', 'title', 'vote_average', 'vote_count', 'release_date',
       'popularity', 'genres', 'cast', 'crew'],
      dtype='object')

In [42]:
# films_df = pre.data_tidying(ohe_films_df, credits_df)
# print(films_df.columns)

Index(['id', 'popularity', 'release_date', 'title', 'vote_average',
       'vote_count', 'Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History',
       'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie',
       'Thriller', 'War', 'Western', 'cast', 'crew'],
      dtype='object')

In [59]:
films_df.sort_values(by='release_date', inplace=True, ascending=False)
films_df.head()

,id,title,vote_average,vote_count,release_date,popularity,genres
304132,447273,Snow White,2.5,22.0,2025-03-19,24.058,"Family, Fantasy"
939885,1297763,Batman Ninja vs. Yakuza League,5.7,22.0,2025-03-17,18.282,"Animation, Action"
1042445,1417677,Bill Burr: Drop Dead Years,7.9,15.0,2025-03-14,6.094,Comedy
816002,1149167,High Rollers,7.4,18.0,2025-03-14,5.812,"Action, Crime, Thriller"
720478,1013482,Borderline,6.2,28.0,2025-03-14,6.613,"Comedy, Horror, Thriller"

In [62]:
# get film 100 in all 3 datasets
films_df[films_df['id'] == 100]

,id,title,vote_average,vote_count,release_date,popularity,genres
65,100,"Lock, Stock and Two Smoking Barrels",8.115,6692.0,1998-08-28,1.946,"Comedy, Crime"

In [ ]:
ratings_df[ratings_df['movieId'] == 100]

In [ ]:
credits_df[credits_df['id'] == 100]

In [66]:
credits_df.columns

Index(['cast', 'crew', 'id'], dtype='object')

In [68]:
ratings_df.columns

Index(['userId', 'movieId', 'rating'], dtype='object')

In [67]:
films_df.sort_values(by='release_date', inplace=True, ascending=False)
films_df.head()

,id,title,vote_average,vote_count,release_date,popularity,genres
304132,447273,Snow White,2.5,22.0,2025-03-19,24.058,"Family, Fantasy"
939885,1297763,Batman Ninja vs. Yakuza League,5.7,22.0,2025-03-17,18.282,"Animation, Action"
1042445,1417677,Bill Burr: Drop Dead Years,7.9,15.0,2025-03-14,6.094,Comedy
816002,1149167,High Rollers,7.4,18.0,2025-03-14,5.812,"Action, Crime, Thriller"
720478,1013482,Borderline,6.2,28.0,2025-03-14,6.613,"Comedy, Horror, Thriller"

In [63]:
# Find common movieIds
common_movie_ids = (set(films_df['id'])
                    # .intersection(set(ratings_df['movieId']))
                    .intersection(set(credits_df['id'])))

# Filter datasets to include only common movieIds
filtered_films_df = films_df[films_df['id'].isin(common_movie_ids)]
filtered_ratings_df = ratings_df[ratings_df['movieId'].isin(common_movie_ids)]
filtered_credits_df = credits_df[credits_df['id'].isin(common_movie_ids)]

# Count the number of entries in each filtered dataset
num_films = len(filtered_films_df)
num_ratings = len(filtered_ratings_df)
num_credits = len(filtered_credits_df)

print(f"Number of films: {num_films}")
print(f"Number of ratings: {num_ratings}")
print(f"Number of credits: {num_credits}")

Number of films: 37693
Number of ratings: 12277326
Number of credits: 37727

In [32]:
#  Number of films: 31865
# Number of ratings: 8543782
# Number of credits: 31823

In [64]:
# Get all the films, filtered by the common movieIds
# Get all the films, filtered by the common movieIds
filtered_films_df.sort_values(by='release_date', inplace=True, ascending=False)

/var/folders/lr/44zcpqfx2196g_qy5t3kc7m40000gp/T/ipykernel_10563/2682610168.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_films_df.sort_values(by='release_date', inplace=True, ascending=False)

In [65]:
filtered_films_df.head()

,id,title,vote_average,vote_count,release_date,popularity,genres
53920,76600,Avatar: The Way of Water,7.607,12351.0,2022-12-14,4.755,"Science Fiction, Adventure, Action"
140696,245842,The King's Daughter,7.100,680.0,2022-01-21,21.104,"Fantasy, Adventure, Family"
24458,38700,Bad Boys for Life,7.100,8354.0,2020-01-15,65.931,"Thriller, Action, Crime"
186037,302349,Iron Sky: The Coming Race,5.100,406.0,2019-01-25,4.040,"Action, Comedy, Fantasy, Science Fiction"
314201,459928,12 Feet Deep,6.000,293.0,2018-11-08,19.892,Thriller