In [1]:

import preprocessing as pre
import pandas as pd
import data_loader
import user_profile as user_pf

In [2]:
# Load the data
films_df = data_loader.load_movies()
ratings_df = data_loader.load_ratings()
credits_df = data_loader.load_credits()

/Users/Cathal/Rec-Genie/rec-sys/data_loader.py:15: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(dataset_path + "/movies_metadata.csv", usecols=['id', 'title', 'release_date', 'genres', 'popularity', 'vote_average', 'vote_count'])

In [18]:
films_df.head()

,id,popularity,release_date,title,vote_average,vote_count,Action,Adventure,Animation,Comedy,...,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western,cast,crew
26620,76600,6.020055,2020-12-16,Avatar 2,0.0,58.0,1,1,0,0,...,0,0,0,1,0,0,0,0,"[{'cast_id': 47, 'character': 'Ronal', 'credit...","[{'credit_id': '52fe4943c3a368484e122b45', 'de..."
38953,299782,0.238154,2018-12-31,The Other Side of the Wind,0.0,1.0,0,0,0,1,...,0,0,0,0,0,0,0,0,"[{'cast_id': 21, 'character': 'J.J. Jake Hanna...","[{'credit_id': '54516d4b0e0a2601d8004b8a', 'de..."
30466,38700,2.178546,2018-11-07,Bad Boys for Life,0.0,12.0,1,0,0,0,...,0,0,0,0,0,1,0,0,"[{'cast_id': 0, 'character': 'Detective Mike L...","[{'credit_id': '585fcddd92514115cd01d8c8', 'de..."
38197,332283,3.328261,2018-04-25,Mary Shelley,0.0,1.0,0,0,0,0,...,0,0,1,0,0,0,0,0,"[{'cast_id': 2, 'character': 'Mary Shelley', '...","[{'credit_id': '588f287ac3a36860d1005f7a', 'de..."
44604,412059,0.155147,2018-04-04,Mobile Homes,0.0,1.0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[{'cast_id': 0, 'character': 'Ali', 'credit_id...","[{'credit_id': '57b78978c3a36823a60029a8', 'de..."

In [3]:

print("Data dimensions:")
print("films_df: ", films_df.shape)
print("ratings_df: ", ratings_df.shape)
print("credits_df: ", credits_df.shape)

Data dimensions:
films_df:  (45466, 7)
ratings_df:  (32000204, 3)
credits_df:  (45476, 3)

In [4]:
ohe_films_df, genre_list_mlb = pre.one_hot_encode_genres(films_df)

In [5]:
films_df = pre.data_tidying(ohe_films_df, credits_df)
print(films_df.columns)

Index(['id', 'popularity', 'release_date', 'title', 'vote_average',
       'vote_count', 'Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History',
       'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie',
       'Thriller', 'War', 'Western', 'cast', 'crew'],
      dtype='object')

In [6]:
# remove all films released before 1985
films_df = films_df[pd.to_datetime(films_df['release_date']).dt.year >= 1985]

In [17]:
films_df.sort_values(by='release_date', inplace=True, ascending=False)
films_df.head()

,id,popularity,release_date,title,vote_average,vote_count,Action,Adventure,Animation,Comedy,...,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western,cast,crew
26620,76600,6.020055,2020-12-16,Avatar 2,0.0,58.0,1,1,0,0,...,0,0,0,1,0,0,0,0,"[{'cast_id': 47, 'character': 'Ronal', 'credit...","[{'credit_id': '52fe4943c3a368484e122b45', 'de..."
38953,299782,0.238154,2018-12-31,The Other Side of the Wind,0.0,1.0,0,0,0,1,...,0,0,0,0,0,0,0,0,"[{'cast_id': 21, 'character': 'J.J. Jake Hanna...","[{'credit_id': '54516d4b0e0a2601d8004b8a', 'de..."
30466,38700,2.178546,2018-11-07,Bad Boys for Life,0.0,12.0,1,0,0,0,...,0,0,0,0,0,1,0,0,"[{'cast_id': 0, 'character': 'Detective Mike L...","[{'credit_id': '585fcddd92514115cd01d8c8', 'de..."
38197,332283,3.328261,2018-04-25,Mary Shelley,0.0,1.0,0,0,0,0,...,0,0,1,0,0,0,0,0,"[{'cast_id': 2, 'character': 'Mary Shelley', '...","[{'credit_id': '588f287ac3a36860d1005f7a', 'de..."
44604,412059,0.155147,2018-04-04,Mobile Homes,0.0,1.0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[{'cast_id': 0, 'character': 'Ali', 'credit_id...","[{'credit_id': '57b78978c3a36823a60029a8', 'de..."

In [7]:
# get film 100 in all 3 datasets
films_df[films_df['id'] == 100]

,id,popularity,release_date,title,vote_average,vote_count,Action,Adventure,Animation,Comedy,...,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western,cast,crew
2433,100,4.60786,1998-03-05,"Lock, Stock and Two Smoking Barrels",7.5,1671.0,0,0,0,1,...,0,0,0,0,0,0,0,0,"[{'cast_id': 12, 'character': 'Tom', 'credit_i...","[{'credit_id': '52fe4217c3a36847f80035c1', 'de..."

In [8]:
ratings_df[ratings_df['movieId'] == 100]

          userId  movieId  rating
8269          57      100     2.0
21395        143      100     1.0
24092        161      100     3.0
26044        179      100     3.0
32121        211      100     4.0
...          ...      ...     ...
31961407  200688      100     4.0
31974394  200764      100     3.0
31991852  200892      100     3.0
31996362  200923      100     3.0
31998528  200939      100     3.0

[4154 rows x 3 columns]

In [9]:
credits_df[credits_df['id'] == 100]

,cast,crew,id
2429,"[{'cast_id': 12, 'character': 'Tom', 'credit_i...","[{'credit_id': '52fe4217c3a36847f80035c1', 'de...",100

In [10]:
credits_df.columns

Index(['cast', 'crew', 'id'], dtype='object')

In [12]:
# Find common movieIds
common_movie_ids = (set(films_df['id'])
                    # .intersection(set(ratings_df['movieId']))
                    .intersection(set(credits_df['id'])))

# Filter datasets to include only common movieIds
filtered_films_df = films_df[films_df['id'].isin(common_movie_ids)]
filtered_ratings_df = ratings_df[ratings_df['movieId'].isin(common_movie_ids)]
filtered_credits_df = credits_df[credits_df['id'].isin(common_movie_ids)]

# Count the number of entries in each filtered dataset
num_films = len(filtered_films_df)
num_ratings = len(filtered_ratings_df)
num_credits = len(filtered_credits_df)

print(f"Number of films: {num_films}")
print(f"Number of ratings: {num_ratings}")
print(f"Number of credits: {num_credits}")

Number of films: 31865
Number of ratings: 8543782
Number of credits: 31823

In [ ]:
 #

In [15]:
# Get all the films, filtered by the common movieIds
# Get all the films, filtered by the common movieIds
filtered_films_df.sort_values(by='release_date', inplace=True, ascending=False)

In [16]:
filtered_films_df.head()

,id,popularity,release_date,title,vote_average,vote_count,Action,Adventure,Animation,Comedy,...,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western,cast,crew
26620,76600,6.020055,2020-12-16,Avatar 2,0.0,58.0,1,1,0,0,...,0,0,0,1,0,0,0,0,"[{'cast_id': 47, 'character': 'Ronal', 'credit...","[{'credit_id': '52fe4943c3a368484e122b45', 'de..."
38953,299782,0.238154,2018-12-31,The Other Side of the Wind,0.0,1.0,0,0,0,1,...,0,0,0,0,0,0,0,0,"[{'cast_id': 21, 'character': 'J.J. Jake Hanna...","[{'credit_id': '54516d4b0e0a2601d8004b8a', 'de..."
30466,38700,2.178546,2018-11-07,Bad Boys for Life,0.0,12.0,1,0,0,0,...,0,0,0,0,0,1,0,0,"[{'cast_id': 0, 'character': 'Detective Mike L...","[{'credit_id': '585fcddd92514115cd01d8c8', 'de..."
38197,332283,3.328261,2018-04-25,Mary Shelley,0.0,1.0,0,0,0,0,...,0,0,1,0,0,0,0,0,"[{'cast_id': 2, 'character': 'Mary Shelley', '...","[{'credit_id': '588f287ac3a36860d1005f7a', 'de..."
44604,412059,0.155147,2018-04-04,Mobile Homes,0.0,1.0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[{'cast_id': 0, 'character': 'Ali', 'credit_id...","[{'credit_id': '57b78978c3a36823a60029a8', 'de..."